# Generated by Django 5.1.4 on 2024-12-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Latex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latex_code', models.TextField(max_length=9999999999999)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
