# Generated by Django 5.1.4 on 2024-12-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latex_code', models.TextField(max_length=9999999999999)),
                ('date', models.DateTimeField()),
                ('history', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Latex',
        ),
    ]
