# Generated by Django 5.1.4 on 2024-12-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_formula_delete_latex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formula',
            old_name='latex_code',
            new_name='latexCode',
        ),
        migrations.RenameField(
            model_name='formula',
            old_name='history',
            new_name='parameters',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='date',
        ),
        migrations.AddField(
            model_name='formula',
            name='initialUserInput',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
